### ISSUE TITLE
Autocomplete not working?

### ISSUE THREAD

**Issue by kurainisei** [antiboredom/p5.vscode#11]
Hi there!
I've just installed the extension and created my first project but for some reason autocomplete is not working.
I tried to change the sketch.js file from js to Typescript (since in the description it says that autocomplete works through typescript) but unfortunately I'm no typescript expert. Is there something else I missed and I need to set up in order to make autocomplete and reference work?
Thanks!

**Comment by antiboredom** [comment]
Hi @kurainisei ! it should work with the sketch.js file as is - no need to switch to Typescript. Can you confirm that there's a file called `jsconfig.json` in your project folder? If so, can you paste it's contents into a comment here?

**Comment by kurainisei** [comment]
Uhm, no, there is no jsconfig.json file in the project folder. Maybe I'll try again and see if it creates it?

**Comment by kurainisei** [comment]
Sure, it's version 1.2.2 on Windows 10 (with latest updates). I also tried to reinstall the extension but it's still not working.

**Comment by antiboredom** [comment]
Must be a bug then! I haven’t tested properly on windows... I’ll see if I can fix it up this weekend.

**Comment by antiboredom** [comment]
@kurainisei I think this should be fixed now - can you update to the latest and see if it works?

**Comment by kurainisei** [comment]
Yes, it works now!
Thank you for the support!
