### ISSUE TITLE
saveTable issue

### ISSUE THREAD

**Issue by PandaBalls** [antiboredom/p5.vscode#18]
loadTable as table,
table.set() some values,
print(table) looks fine.
But saveTable(table) throw this error:

```
p5.min.js:3 Uncaught TypeError: e.rows[l].arr[u].includes is not a function
    at _.y.default.saveTable (p5.min.js:3)
    at <anonymous>:1:1
```

only happened in p5.vscode.
It works fine in Processing Desktop IDE

**Comment by antiboredom** [comment]
Hi - it looks like this is actually a bug in the latest version of p5js (1.2.0). I suggest logging a bug at the p5js repo and in the meantime you can use version 1.1.9 by replacing p5.min.js with this file: https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.1.9/p5.min.js
