### ISSUE TITLE
Packaged Version of P5js Outdated

### ISSUE THREAD

**Issue by stungeye** [antiboredom/p5.vscode#26]
Hi. Thanks for creating this handy plugin. I love how easy it makes setting up a new p5 project.

Currently this plugin uses p5.js v1.2.0 from Dec 2020. I'd love to see the plugin updated to use the latest version, v1.3.1 from March 2021. 

I also left a comment on your [Automatically update and publish when p5 updates](https://github.com/antiboredom/p5.vscode/issues/6) issue with a suggestion that might remove the need to keep up with p5 versions.

**Comment by antiboredom** [comment]
Thanks - just updated it! and I will take a look at that other issue...

**Comment by stungeye** [comment]
Thanks for the incredibly quick response!!!
