### ISSUE TITLE
Autocomplete stopped working

### ISSUE THREAD

**Issue by SolaireOfUnity** [antiboredom/p5.vscode#29]
After a 2 day pause i came back to my project to find that simple commands like "Fill" and "Stroke" do not get recognised by the autocomplete anymore and I don't know why.

**Comment by cgiles** [comment]
I have the same issue.

**Comment by antiboredom** [comment]
This should be fixex now.

**Comment by cgiles** [comment]
Just came here for said I found what was the cause of the issue.
I checked my jsonconfig.json, and the path was for an earlier version, which wasn't present on my computer anymore (samplavigne.p5-vscode-1.2.8) and once updated to one present on my computer, it worked again !
