### ISSUE TITLE
Console/Audio issue: The AudioContext was not allowed to start.

### ISSUE THREAD

**Issue by zumatt** [antiboredom/p5.vscode#34]
There is an error that prevent to use p5.sound.min.js 
I fix it putting in the file this line of code: function touchStarted() {if (getAudioContext().state !== 'running') {getAudioContext().resume();}}

**Comment by antiboredom** [comment]
Hi - I think this might be an issue with p5 sound and night with this extensions, so you should file the issue on their page: https://github.com/processing/p5.js

Best,
Sam
