### ISSUE TITLE
Error in jsconfig.json

### ISSUE THREAD

**Issue by JoePShoulak** [antiboredom/p5.vscode#50]
I updated VS Code and afterward noticed that VS Code was reporting errors in my jsconfig.json file. I usually notice that sort of thing, so I checked another project, and it's reporting the same error (when I don't think it did before). 

![image](https://user-images.githubusercontent.com/1021647/206335104-e30533b5-f48d-41d6-a1f4-831825a653b4.png)

`File 'c:/Users/joeps/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/lib.d.ts' not found.
  The file is in the program because:
    Default library for target 'es3'`

This error is shown (9 times, for some reason). 

Maybe there was a change to the pathing in the latest update?

**Comment by antiboredom** [comment]
Hi - I'm not getting this but I am also on a mac, and wondering if this might be a bug I introduced in windows only. Can you send me a sample jsconfig.json file?

**Comment by JoePShoulak** [comment]
Absolutely, it looks like this:
`{
  "include": [
    "*.js",
    "**/*.js",
    "c:\\Users\\joeps\\.vscode\\extensions\\samplavigne.p5-vscode-1.2.12\\p5types\\global.d.ts"
  ]
}`

**Comment by antiboredom** [comment]
Thanks! Can you replace all of the double slashes with a single slash (except for the two after “c:”) and let me know if that fixes it?

**Comment by JoePShoulak** [comment]
I believe that fixes it! No errors!

**Comment by antiboredom** [comment]
Great. I‘ll try to push a fix in the next day or so. Thanks for posting the issue and your help in debugging it!

**Comment by JoePShoulak** [comment]
My pleasure! I can't image using p5 in VS Code without the intellisense that your extension provides, this is the least I can do in return!

**Comment by JoePShoulak** [comment]
Hmm, I may have been wrong. This is an error I'm getting with the corrected pathing:

![image](https://user-images.githubusercontent.com/1021647/206524333-4fd55820-ef5c-4034-83ce-e44f0f0f9693.png)

**Comment by chanbinna** [comment]
I am on Mac and I am having same issue too

**Comment by antiboredom** [comment]
well, I'm getting the error now too!

**Comment by JoePShoulak** [comment]
Looks like that did it for me!

**Comment by antiboredom** [comment]
Great - closing the issue now…
