### ISSUE TITLE
Go Live does not work with source files not named "sketch.js"

### ISSUE THREAD

**Issue by dtcitron** [antiboredom/p5.vscode#66]
If I rename my file to something else ("test.js") the Go Live function is unable to render it in browser.

Relatedly, if there are multiple .js files the only one that renders through Go Live is the one named sketch.js.

Is there a way to switch between source files?

**Comment by antiboredom** [comment]
Hi! If you change sketch.js you’ll also need to edit the index.html file to point to the new name of your JavaScript file…

**Comment by dtcitron** [comment]
I'll try that - thanks for the quick response!
