### ISSUE TITLE
Reminder permissions ?

### ISSUE THREAD

**Issue by dhowe** [antiboredom/p5.vscode#7]
Just curious about the permission request I got after installing, asking to access my 'reminders'. Is this related to the plugin or just a coincidence?

![reminders](https://user-images.githubusercontent.com/737638/89247827-c3d52c00-d640-11ea-96f6-47f8d5563030.png)

**Comment by antiboredom** [comment]
That's a strange one! I'm guessing it's a coincidence, maybe related to VS Code accessing your home folder, and that somehow triggering the seemingly-unrelated permission request. But will do some research... What mac version are you running?

**Comment by antiboredom** [comment]
I think this is related: https://github.com/microsoft/vscode/issues/55236

**Comment by dhowe** [comment]
10.15.6 - how goes, btw.. all good?
